---
- name: Déployer l'API Flask sur le noeud
  hosts: webserver
  become: yes
  
  vars:
    app_dir: '/home/ubuntu/flask_app'
    flask_port: 5000

  tasks:
    - name: Installer les dépendances système
      apt:
        name:
          - python3
          - python3-pip
          - git
        state: present
        update_cache: yes

    - name: Ajouter GitHub à known_hosts
      known_hosts:
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
        path: /home/ubuntu/.ssh/known_hosts
        state: present

    - name : Copier la clé SSH
      copy:
        src: files/id_ansible_deploy
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Cloner le dépôt Git
      git:
        repo: git@github.com:Othman-Bargach/backend-flask.git
        dest: '{{ app_dir }}'
        version: main
        force: yes
      environment:
        GIT_SSH_COMMAND: "ssh -i /home/ubuntu/.ssh/id_rsa -o StrictHostKeyChecking=no"

    - name: Installer virtualenv
      apt:
        name: python3-venv
        state: present

    - name: Créer un environnement virtuel
      command: python3 -m venv {{ app_dir }}/venv
      args:
        creates: "{{ app_dir }}/venv/bin/activate"

    - name: Installer les dépendances dans le virtualenv
      command: '{{ app_dir }}/venv/bin/pip install --upgrade -r {{ app_dir }}/requirements.txt'

    - name : ouvrir le port 5000
      ufw:
        rule: allow
        port: '{{ flask_port }}'
        proto: tcp
    
    - name: Lancer l'application Flask
      shell: |
        cd {{ app_dir }}
        nohup ./venv/bin/python ./app.py --host=0.0.0.0 --port=5000 &
