name: Configure EC2 with Ansible

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: pip install ansible

      # Télécharge l'adresse IP publique de l'instance EC2 créée par Terraform depuis les artifacts du workflow précédent
      - name: Download public IP artifact
        uses: actions/download-artifact@v4
        with:
          name: public-ip

      # Lit l'adresse IP publique depuis le fichier texte téléchargé
      - name: Show public IP
        run: cat public_ip.txt

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook
        run: |
          ANSIBLE_HOST=$(cat public_ip.txt)
          ansible-playbook -i "$ANSIBLE_HOST," ansible/playbook.yml --private-key $SSH_AUTH_SOCK -u ubuntu