name: Configure EC2 with Ansible

on:
  push:
    branches: [ "main" ] # Déclenche les jobs lors d’un push sur main. Le push est notre "trigger" pour le workflow
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: pip install ansible

      - name: Get Terraform Outputs
        id: tf-output
        run: |
          cd terraform-aws-instance
          terraform init
          terraform output -raw public_ip > ../public_ip.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Show public IP
        run: cat public_ip.txt

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook
        run: |
          ANSIBLE_HOST=$(cat public_ip.txt)
          ansible-playbook -i "$ANSIBLE_HOST," ansible/playbook.yml --private-key $SSH_AUTH_SOCK -u ubuntu