name: Deploy with Terraform

on:
  ???

jobs:
  Terraform_deploy:
    runs-on: ubuntu-latest

    env:
      TF_INPUT: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - ???
        working-directory: ./terraform-aws-instance

      - ???
        working-directory: ./terraform-aws-instance

      - ???
        working-directory: ./terraform-aws-instance

