name: Deploy with Terraform

on:
  workflow_dispatch:     # Permet le déclenchement manuel dans GitHub

jobs:
  Terraform Apply:
    runs-on: ubuntu-latest

    env:
      TF_INPUT: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Clone le dépôt sur le runner Ubuntu de Github Actions pour accéder aux fichiers Terraform
      - name: Checkout code
        uses: actions/checkout@v4

      # Installe Terraform sur le runner Ubuntu de Github Actions
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - ???
        working-directory: ./terraform-aws-instance

      - ???
        working-directory: ./terraform-aws-instance

      - ???
        working-directory: ./terraform-aws-instance
